
import "./globalCSS/reset.css";
import "./globalCSS/rootVariables.css"
import "./globalCSS/scaffold.css"
import "./globalCSS/utilities.css"
import "./maps/[id]/Mobile/styles.css"
import { signIn } from "./auth";
import { signOut } from "./auth";



export const metadata = {
  title: "Map App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body >
      
        {children}
        <div id="menu-container"></div>
        <div id="portal-container"></div>
     
        
      </body>
    </html>
  );
}

/*
   <form
      action={async () => {
        "use server"
        await signIn("google",{ redirectTo: "/" })
      }}
    >
      <button type="submit">Signin with Google</button>
    </form>
    <form
      action={async () => {
        "use server"
        await signOut()
      }}
    >
      <button type="submit">Sign Out</button>
    </form>
    */