
import "./globalCSS/reset.css";
import "./globalCSS/rootVariables.css"
import "./globalCSS/scaffold.scss"
import "./globalCSS/utilities.css"


export const metadata = {
  title: "Map App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      
        {children}
        <div id="portal-container"></div>
      </body>
    </html>
  );
}
